FROM maslick/minimalka:jdk11
VOLUME /tmp
EXPOSE 8081
ADD demojpa-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=container","-jar","/app.jar"]